### ISSUE TITLE
Provider should be able to create organisation and api-key for and org

### ISSUE THREAD

**Issue by naman3305** [akuity/provider-crossplane-akuity#51]
### What problem are you facing?

Right now the akuity provider requires API-Key and credential's to added in the provider config , this requires manually creating an org in self hosted akuity platform and creating api-key for an org. 
We are looking for and end-end deployment of akuity platform but these are the manual steps that we need to perform. 

### How could the Akuity Crossplane Provider help solve your problem?

 Can we get an enhancement in which we can create an org in a self hosted akuity platform and create an API-Key for that org or a new provider only for creating org and API-Key in slef hosted akuity platform.

**Comment by blakepettersson** [comment]
Since this is a thing which is exclusive for our self-hosted edition, it makes more sense for that to be there. We have added support for creating organizations with the 0.17 Helm chart. We still need to add API Key support in the Helm chart.

**Comment by blakepettersson** [comment]
Closing this one for now, since we have an internal task for API Key support.
